### ISSUE TITLE
only open projects are showing

### ISSUE THREAD

**Issue by hanskoff** [erikzielke/GoToProject#4]
HI, I love your plugin and I don't imagine working without it, somehow I lost `recent project` after I call `go to projects` shortcut :( do you know how to restore it? 

[I'm using idea 2016 and removed idea 15 and lost custom settings and after adding gotoproject again I can't make it to show recent projects too]

**Comment by erikzielke** [comment]
hi, thanks :) You are right - seems the settings panel is gone in 2016 - will look into it

**Comment by hanskoff** [comment]
wow, that was quick answer, thx ;)

**Comment by erikzielke** [comment]
found the issue and fixed it - should be available now. So now the option is in preferences > other settings > go to project window

**Comment by hanskoff** [comment]
I'm using 1.1.4 version but unfortunately on osx there still no recent projects?

**Comment by erikzielke** [comment]
And you have enabled the option in setting? By default its disabled

**Comment by hanskoff** [comment]
yeah! works as expected! thnx
