### ISSUE TITLE
Custom project name

### ISSUE THREAD

**Issue by julien-maurel** [erikzielke/GoToProject#5]
Hi,
Do you think it is possible to use custom project name when setted on a project (via File->Rename Project)? 
Else, thanks for your plugin that is very useful!

**Comment by erikzielke** [comment]
Rename Project - is that from a plugin?

The name I use is the name defined in Project Structure -> Project -> Project Name

**Comment by julien-maurel** [comment]
No it's a native feature.
I can just say that in PHPStorn, project renaming is done with File menu->Rename project
And on .idea folder of the project, a ".name" file is created with the new name inside (file is created only if you rename the project and set a name that is different of the default name, in other words different of the project folder name)

**Comment by erikzielke** [comment]
For currently opened projects it already works that way - but after rename you have to reopen the project.

For recent projects - it does not seem to work - but nor does the built-in recent dialog

**Comment by julien-maurel** [comment]
Yes you're right. I thought I restarted it but no :/ Sorry for inconvenience.
About recents, it doesn't work on native features too (welcome screen, recents...) so I think issue is not on your side.
Thanks for your answer and sorry again.
