### ISSUE TITLE
Fast siwtch between two last projects

### ISSUE THREAD

**Issue by AlexKalinin** [erikzielke/GoToProject#7]
To switch between opened projects in RubyMine, I press `Command + Shift + P` -> [optional: enter projectNameMask] --> select project by arrow keys --> press `Enter`. In common way it is fast enough, thank you very match for this plugin. 

But, there is case, when we could speed up project switching. For example, I have opened A, B, C, D and E projects, and I don't want to close them yet. Now I need to copy few files / code blocks from C-project to E-project - I need make 5 - 10 fast switches between C and E. If `Command + Shift + P` window would "remember" last edit project, I'd press `Command+Shift+P -> Enter` and whould got fast C/E project switching. But when I press `Command+Shift+P` the selection of projectChoosingMenu is always positioned at the first Item (A-project), and I have to select by arrow keys project C/E or input projectNameMask. 

The improvement would be in  remembering last edit project and

* positioning the selection in projectChoosingMenu
* or / and
* adding keyboard shortcut to switch between two recently edited projects (like `Cmd + ~` when openedProjects == 2).

Other example is `Command + Tab` in OSX (`Alt + Tab` in Linux/Windows) -- by single shortcut pressings - we are looping in two recent applications windows.

**Comment by Gordondalos** [comment]
+1, I'd like to have this in my PhpStorm too

**Comment by erikzielke** [comment]
It once worked like like that - as in last opened project was always first in the dialog - consistent with ctrl + e for Recent Files - but doesn't seem to work anymore - so I do understand the feature request :)

**Comment by erikzielke** [comment]
I have tried to fix putting last project window in top on list
And also made a Go To Last Project-action

**Comment by AlexKalinin** [comment]
It works, thanks! :tada: :tada: :tada:
